// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xMt51hRRAly6Gbz3XXYXyIffv_JLeSE',
    appId: '1:79250608231:web:cd70f7200c9e9c639f04c2',
    messagingSenderId: '79250608231',
    projectId: 'fir-auth-a2bf7',
    authDomain: 'fir-auth-a2bf7.firebaseapp.com',
    storageBucket: 'fir-auth-a2bf7.appspot.com',
    measurementId: 'G-QD4LX283QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR_BGmaec5SHCCYq_mQ-4TRCx49huBwHI',
    appId: '1:79250608231:android:32a07fb4cb866c339f04c2',
    messagingSenderId: '79250608231',
    projectId: 'fir-auth-a2bf7',
    storageBucket: 'fir-auth-a2bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL4rs7TuN1j5A58uLDzkTUVnP0QWZ9fPA',
    appId: '1:79250608231:ios:25946a6bca623fb69f04c2',
    messagingSenderId: '79250608231',
    projectId: 'fir-auth-a2bf7',
    storageBucket: 'fir-auth-a2bf7.appspot.com',
    iosBundleId: 'com.example.flutterFoodies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL4rs7TuN1j5A58uLDzkTUVnP0QWZ9fPA',
    appId: '1:79250608231:ios:cef5b98a52d71d809f04c2',
    messagingSenderId: '79250608231',
    projectId: 'fir-auth-a2bf7',
    storageBucket: 'fir-auth-a2bf7.appspot.com',
    iosBundleId: 'com.example.flutterFoodies.RunnerTests',
  );
}
